# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/exrxnet/exercise.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.exrxnet import muscle_pb2 as proto_dot_exrxnet_dot_muscle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/exrxnet/exercise.proto\x12\x10workouts.exrxnet\x1a\x1aproto/exrxnet/muscle.proto\"\x96\x03\n\x08\x45xercise\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x35\n\x05\x66orce\x18\x03 \x01(\x0e\x32&.workouts.exrxnet.Exercise.MuscleForce\x12+\n\tsynergist\x18\x04 \x03(\x0b\x32\x18.workouts.exrxnet.Muscle\x12,\n\nstabilizer\x18\x05 \x03(\x0b\x32\x18.workouts.exrxnet.Muscle\x12\x34\n\x12\x64ynamic_stabilizer\x18\x06 \x03(\x0b\x32\x18.workouts.exrxnet.Muscle\x12\x37\n\x15\x61ntagonist_stabilizer\x18\x07 \x03(\x0b\x32\x18.workouts.exrxnet.Muscle\x12\x14\n\x0cinstructions\x18\x08 \x01(\t\"Y\n\x0bMuscleForce\x12\x1c\n\x18MUSCLE_FORCE_UNSPECIFIED\x10\x00\x12\x15\n\x11MUSCLE_FORCE_PULL\x10\x01\x12\x15\n\x11MUSCLE_FORCE_PUSH\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.exrxnet.exercise_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXERCISE._serialized_start=79
  _EXERCISE._serialized_end=485
  _EXERCISE_MUSCLEFORCE._serialized_start=396
  _EXERCISE_MUSCLEFORCE._serialized_end=485
# @@protoc_insertion_point(module_scope)
