# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bodybuildingcom/equipment.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%proto/bodybuildingcom/equipment.proto\x12\x18workouts.bodybuildingcom*\xc1\x04\n\tEquipment\x12\x19\n\x15\x45QUIPMENT_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x45QUIPMENT_BANDS\x10\x01\x12\x15\n\x11\x45QUIPMENT_BARBELL\x10\x02\x12\x17\n\x13\x45QUIPMENT_BODY_ONLY\x10\x03\x12\x19\n\x15\x45QUIPMENT_BODY_WEIGHT\x10\x04\x12\x17\n\x13\x45QUIPMENT_BOSU_BALL\x10\x05\x12\x13\n\x0f\x45QUIPMENT_CABLE\x10\x06\x12\x1b\n\x17\x45QUIPMENT_CABLE_MACHINE\x10\x07\x12\x14\n\x10\x45QUIPMENT_CABLES\x10\x08\x12\x16\n\x12\x45QUIPMENT_CURL_BAR\x10\t\x12\x16\n\x12\x45QUIPMENT_DUMBBELL\x10\n\x12\x17\n\x13\x45QUIPMENT_DUMBBELLS\x10\x0b\x12\x1b\n\x17\x45QUIPMENT_EXERCISE_BALL\x10\x0c\x12\x1a\n\x16\x45QUIPMENT_E_Z_CURL_BAR\x10\r\x12\x17\n\x13\x45QUIPMENT_FOAM_ROLL\x10\x0e\x12\x19\n\x15\x45QUIPMENT_KETTLEBELLS\x10\x0f\x12\x16\n\x12\x45QUIPMENT_LANDMINE\x10\x10\x12\x15\n\x11\x45QUIPMENT_MACHINE\x10\x11\x12\x11\n\rEQUIPMENT_MAT\x10\x12\x12\x1b\n\x17\x45QUIPMENT_MEDICINE_BALL\x10\x13\x12\x12\n\x0e\x45QUIPMENT_NONE\x10\x14\x12\x13\n\x0f\x45QUIPMENT_OTHER\x10\x15\x12\x1a\n\x16\x45QUIPMENT_WEIGHT_BENCH\x10\x16\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bodybuildingcom.equipment_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EQUIPMENT._serialized_start=68
  _EQUIPMENT._serialized_end=645
# @@protoc_insertion_point(module_scope)
