# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bodybuildingcom/exercise.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.bodybuildingcom import muscle_pb2 as proto_dot_bodybuildingcom_dot_muscle__pb2
from proto.bodybuildingcom import equipment_pb2 as proto_dot_bodybuildingcom_dot_equipment__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/bodybuildingcom/exercise.proto\x12\x18workouts.bodybuildingcom\x1a\"proto/bodybuildingcom/muscle.proto\x1a%proto/bodybuildingcom/equipment.proto\"\xdb\x01\n\x08\x45xercise\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x30\n\x06muscle\x18\x03 \x01(\x0e\x32 .workouts.bodybuildingcom.Muscle\x12\x36\n\tequipment\x18\x04 \x01(\x0e\x32#.workouts.bodybuildingcom.Equipment\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08\x62\x65nefits\x18\x06 \x01(\t\x12\x14\n\x0cinstructions\x18\x07 \x01(\t\x12\x0e\n\x06rating\x18\x08 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bodybuildingcom.exercise_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXERCISE._serialized_start=142
  _EXERCISE._serialized_end=361
# @@protoc_insertion_point(module_scope)
