# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bodybuildingcom/muscle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/bodybuildingcom/muscle.proto\x12\x18workouts.bodybuildingcom*\xfe\x02\n\x06Muscle\x12\x16\n\x12MUSCLE_UNSPECIFIED\x10\x00\x12\x15\n\x11MUSCLE_ABDOMINALS\x10\x01\x12\x14\n\x10MUSCLE_ABDUCTORS\x10\x02\x12\x14\n\x10MUSCLE_ADDUCTORS\x10\x03\x12\x11\n\rMUSCLE_BICEPS\x10\x04\x12\x11\n\rMUSCLE_CALVES\x10\x05\x12\x10\n\x0cMUSCLE_CHEST\x10\x06\x12\x13\n\x0fMUSCLE_FOREARMS\x10\x07\x12\x11\n\rMUSCLE_GLUTES\x10\x08\x12\x15\n\x11MUSCLE_HAMSTRINGS\x10\t\x12\x0f\n\x0bMUSCLE_LATS\x10\n\x12\x15\n\x11MUSCLE_LOWER_BACK\x10\x0b\x12\x16\n\x12MUSCLE_MIDDLE_BACK\x10\x0c\x12\x0f\n\x0bMUSCLE_NECK\x10\r\x12\x15\n\x11MUSCLE_QUADRICEPS\x10\x0e\x12\x14\n\x10MUSCLE_SHOULDERS\x10\x0f\x12\x10\n\x0cMUSCLE_TRAPS\x10\x10\x12\x12\n\x0eMUSCLE_TRICEPS\x10\x11\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bodybuildingcom.muscle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUSCLE._serialized_start=65
  _MUSCLE._serialized_end=447
# @@protoc_insertion_point(module_scope)
