# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: muscle.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmuscle.proto\x12\x10workouts.exrxnet\"\xe6\x06\n\x06Muscle\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x31\n\x04part\x18\x03 \x01(\x0e\x32#.workouts.exrxnet.Muscle.MusclePart\x12\x39\n\x08position\x18\x04 \x01(\x0e\x32\'.workouts.exrxnet.Muscle.MusclePosition\x12\x37\n\x07segment\x18\x05 \x01(\x0e\x32&.workouts.exrxnet.Muscle.MuscleSegment\"\x94\x02\n\nMusclePart\x12\x1b\n\x17MUSCLE_PART_UNSPECIFIED\x10\x00\x12\x14\n\x10MUSLCE_PART_BACK\x10\x01\x12\x16\n\x12MUSLCE_PART_CALVES\x10\x02\x12\x15\n\x11MUSLCE_PART_CHEST\x10\x03\x12\x18\n\x14MUSLCE_PART_FOREARMS\x10\x04\x12\x14\n\x10MUSLCE_PART_HIPS\x10\x05\x12\x14\n\x10MUSLCE_PART_NECK\x10\x06\x12\x19\n\x15MUSLCE_PART_SHOULDERS\x10\x07\x12\x15\n\x11MUSLCE_PART_THIGH\x10\x08\x12\x15\n\x11MUSLCE_PART_UPPER\x10\t\x12\x15\n\x11MUSLCE_PART_WAIST\x10\n\"f\n\x0eMusclePosition\x12\x1f\n\x1bMUSCLE_POSITION_UNSPECIFIED\x10\x00\x12\x18\n\x14MUSCLE_POSITION_BACK\x10\x01\x12\x19\n\x15MUSCLE_POSITION_FRONT\x10\x02\"\x9b\x02\n\rMuscleSegment\x12\x1e\n\x1aMUSCLE_SEGMENT_UNSPECIFIED\x10\x00\x12\x1a\n\x16MUSCLE_SEGMENT_ABDOMEN\x10\x01\x12\x1a\n\x16MUSCLE_SEGMENT_FOREARM\x10\x02\x12\x17\n\x13MUSCLE_SEGMENT_HEAD\x10\x03\x12\x16\n\x12MUSCLE_SEGMENT_LEG\x10\x04\x12\x17\n\x13MUSCLE_SEGMENT_NECK\x10\x05\x12\x19\n\x15MUSCLE_SEGMENT_PELVIS\x10\x06\x12\x18\n\x14MUSCLE_SEGMENT_THIGH\x10\x07\x12\x19\n\x15MUSCLE_SEGMENT_THORAX\x10\x08\x12\x18\n\x14MUSCLE_SEGMENT_UPPER\x10\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'muscle_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MUSCLE._serialized_start=35
  _MUSCLE._serialized_end=905
  _MUSCLE_MUSCLEPART._serialized_start=239
  _MUSCLE_MUSCLEPART._serialized_end=515
  _MUSCLE_MUSCLEPOSITION._serialized_start=517
  _MUSCLE_MUSCLEPOSITION._serialized_end=619
  _MUSCLE_MUSCLESEGMENT._serialized_start=622
  _MUSCLE_MUSCLESEGMENT._serialized_end=905
# @@protoc_insertion_point(module_scope)
