load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
  name = "exercise_proto",
  srcs = ["exercise.proto"],
  deps = ["//proto:muscle_proto"],
)

proto_library(
  name = "muscle_proto",
  srcs = ["muscle.proto"],
)
