# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xercise.proto\x12\x08workouts\"\x9f\x02\n\x08\x45xercise\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x17\n\x0fpreferred_alias\x18\x02 \x01(\t\x12P\n\x18muscle_weight_percentage\x18\x03 \x03(\x0b\x32..workouts.Exercise.MuscleWeightPercentageEntry\x12\'\n\x1fpercentage_of_bodyweight_lifted\x18\x04 \x01(\x02\x12\x32\n*percentage_of_bodyweight_lifted_source_url\x18\x05 \x01(\t\x1a=\n\x1bMuscleWeightPercentageEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exercise_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXERCISE_MUSCLEWEIGHTPERCENTAGEENTRY._options = None
  _EXERCISE_MUSCLEWEIGHTPERCENTAGEENTRY._serialized_options = b'8\001'
  _EXERCISE._serialized_start=29
  _EXERCISE._serialized_end=316
  _EXERCISE_MUSCLEWEIGHTPERCENTAGEENTRY._serialized_start=255
  _EXERCISE_MUSCLEWEIGHTPERCENTAGEENTRY._serialized_end=316
# @@protoc_insertion_point(module_scope)
